
BASE_URL = 'http://services.runescape.com/m=hiscore_oldschool'
STATS_URL = 'index_lite.ws?player='
SCORES_URL = 'overall.ws?'
GAMEMODE_URL = {
  'dmm': '_deadman/',
  'dmmt': '_tournament/',
  'hc': '_hardcore_ironman/',
  'iron': '_ironman/',
  'main': '/',
  'sdmm': '_seasonal/',
  'ult': '_ultimate/',
}
SKILLS = [
  'Overall',
  'Attack',
  'Defence',
  'Strength',
  'Hitpoints',
  'Ranged',
  'Prayer',
  'Magic',
  'Cooking',
  'Woodcutting',
  'Fletching',
  'Fishing',
  'Firemaking',
  'Crafting',
  'Smithing',
  'Mining',
  'Herblore',
  'Agility',
  'Thieving',
  'Slayer',
  'Farming',
  'Runecraft',
  'Hunter',
  'Construction',
]
CLUES = [
  'Total',
  'Beginner',
  'Easy',
  'Medium',
  'Hard',
  'Elite',
  'Master',
]

BOSSES = [
'Abyssal Sire',
'Alchemical Hydra',
'Barrows Chests',
'Bryophyta',
# 'Callisto',
# 'Cerberus',
'Chambers of Xeric',
'Chambers of Xeric: Challenge Mode',
'Chaos Elemental',
'Chaos Fanatic',
'Commander Zilyana',
'Corporeal Beast',
'Crazy Archaeologist',
'Dagannoth Prime',
'Dagannoth Rex',
'Dagannoth Supreme',
'Deranged Archaeologist',
'General Graardor',
'Giant Mole',
'Grotesque Guardians',
'Hespori',
'Kalphite Queen',
'King Black Dragon',
'Kraken',
"Kree'Arra",
"K'ril Tsutsaroth",
"Mimic",
"Obor",
"Sarachnis",
"Scorpia",
"Skotizo",
"The Gauntlet",
"The Corrupted Gauntlet",
"Theatre of Blood",
"Thermonuclear Smoke Devil",
"TzKal-Zuk",
"TzTok-Jad",
"Venenatis",
"Vet'ion",
"Vorkath",
"Wintertodt",
"Zalcano",
"Zulrah"
]

boss_shorts = {
"corp":"CorporealBeast",
"jad":"TzTokJad",
"kq":"KalphiteQueen",
"chaosele":"ChaosElemental",
"crazyarch":"CrazyArchaeologist",
"derangedarch":"DerangedArchaeologist",
"mole":"GiantMole",
"vetion":"Vetion",
"vene":"Venenatis",
"kbd":"KingBlackDragon",
"vork":"Vorkath",
"sire":"AbyssalSire",
"cerb":"Cerberus",
"supreme":"DagannothSupreme",
"rex":"DagannothRex",
"prime":"DagannothPrime",
"wt":"Wintertodt",
"barrows":"BarrowsChests",
"dusk":"GrotesqueGuardians",
"dawn":"GrotesqueGuardians",
"gargs":"GrotesqueGuardians",
"smokedevil":"ThermonuclearSmokeDevil",
"thermy":"ThermonuclearSmokeDevil",
"inferno":"TzKalZuk",
"zuk":"TzKalZuk",
"sara":"CommanderZilyana",
"zily":"CommanderZilyana",
"zilyana":"CommanderZilyana",
"saradomin":"CommanderZilyana",
"zammy":"KrilTsutsaroth",
"kriltrutsaroth":"KrilTsutsaroth",
"kril":"KrilTsutsaroth",
"zamorak":"KrilTsutsaroth",
"arma":"Kreearra",
"armadyl":"Kreearra",
"kreearra":"Kreearra",
"kree":"Kreearra",
"bandos":"GeneralGraardor",
"graardor":"GeneralGraardor",
"cox":"ChambersofXeric",
"raids":"ChambersofXeric",
"raidscm":"ChambersofXeric:ChallengeMode",
"coxcm":"ChambersofXeric:ChallengeMode",
"tob":"TheatreofBlood",
"raids2":"TheatreofBlood",
"beg":"Beginner",
"med":"Medium"
}

STATSINDEX = {"Overall":2,
"Total":3,
"Beginner":4,
"Easy":5,
"Medium":6,
"Hard":7,
"Elite":8,
"Master":9,
"Abyssal Sire":10,
"Alchemical Hydra":11,
"Barrows Chests":12,
"Bryophyta":13,
"Chambers of Xeric":14,
"Chambers of Xeric: Challenge Mode":15,
"Chaos Elemental":16,
"Chaos Fanatic":17,
"Commander Zilyana":18,
"Corporeal Beast":19,
"Crazy Archaeologist":20,
"Dagannoth Prime":21,
"Dagannoth Rex":22,
"Dagannoth Supreme":23,
"Deranged Archaeologist":24,
"General Graardor":25,
"Giant Mole":26,
"Grotesque Guardians":27,
"Hespori":28,
"Kalphite Queen":29,
"King Black Dragon":30,
"Kraken":31,
"Kree'Arra":32,
"K'ril Tsutsaroth":33,
"Mimic":34,
"Obor":35,
"Sarachnis":36,
"Scorpia":37,
"Skotizo":38,
"The Gauntlet":39,
"The Corrupted Gauntlet":40,
"Theatre of Blood":41,
"Thermonuclear Smoke Devil":42,
"TzKal-Zuk":43,
"TzTok-Jad":44,
"Venenatis":45,
"Vet'ion":46,
"Vorkath":47,
"Wintertodt":48,
"Zalcano":49,
"Zulrah":50}
